/*
    Secure Credentials
*/

#ifndef _SECURE_CREDENTIALS_H_
#define _SECURE_CREDENTIALS_H_


const char CA_CERT_PROG[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDnTCCAoWgAwIBAgIJAMA06vSmgMOiMA0GCSqGSIb3DQEBCwUAMGUxFzAVBgNV
BAMMDkFuIE1RVFQgYnJva2VyMRIwEAYDVQQKDAlob3B0by5vcmcxFDASBgNVBAsM
C2FsYnJvc190ZWFtMSAwHgYJKoZIhvcNAQkBFhFhbGJraXJrQGdtYWlsLmNvbTAe
Fw0yMDA2MTUwNzUxNDRaFw0zMjA2MTIwNzUxNDRaMGUxFzAVBgNVBAMMDkFuIE1R
VFQgYnJva2VyMRIwEAYDVQQKDAlob3B0by5vcmcxFDASBgNVBAsMC2FsYnJvc190
ZWFtMSAwHgYJKoZIhvcNAQkBFhFhbGJraXJrQGdtYWlsLmNvbTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBALdWjHdHekwzQZdeoZSLWTUN5HCshwuCOtU6
SQIXsU8JqSA1EE642HFZG3pLgrzwFAoUux+iEz/SvCbwc0BJKqWA8Wqy7E/b2p6q
AJXIvFQnRVxhUfgKzzAe1gArP9nG3b+vA6fnVHWV+fhNHtZaQkNKh2/MF8LhdVmU
JXFBdD+1wz6mcrtaE8cwFYcYqw1ty7AzaVmFsqLFgvLHDKlROrSLeOYOLTy2yJF3
KaHkLFqI8S5SYDhD6vhMloIDZrggpwxBRR3hJDvIwj5SvccYoUn1JSRF3UhWlVdf
nzxIKnmgM0YvFgLKWkCw4QtA+LfX41hP6HS3yRx3VIRA+TCbw6sCAwEAAaNQME4w
HQYDVR0OBBYEFBrDldcxMIPoHiclUzatK3/lGDDDMB8GA1UdIwQYMBaAFBrDldcx
MIPoHiclUzatK3/lGDDDMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AK798o727SX77Tb9vdL94YPDECPhuLnbY8MhzTVGjNX3bvPXk59sMjX7p2nSJ+L+
PxBr1NhH5ydEkXx7XvfYPwe5Z7V1RAdq0qRHtRML02P83fesS7lHk3nSY03ZTDHA
IgdQBdk8y0wBVR8WgGKskiKTkjz6my8E846egx0r+qdmTS2NN5/y+w/Ik/WXoNZf
29qKCBnESW3Vd9VB78DDi8ggD9/3+nyroUi3sX+l4iVv+67dC9fDrY02EW8phJdU
BsKnjJ98Jqwros7KXc+rc4n4FxjjT6O4jWTmNpJHiEv0c44HIOlnZOf4/3kwWtiG
pDzw10DidRlZ2rGtsp+Aj70=
-----END CERTIFICATE-----
)EOF";

const char CLIENT_CERT_PROG[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
... your certificate goes here ...
-----END CERTIFICATE-----
)EOF";

// KEEP THIS VALUE PRIVATE AND SECURE!!!
const char CLIENT_KEY_PROG[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
... your private key goes here ...
-----END RSA PRIVATE KEY-----
)KEY";




#endif // _SECURE_CREDENTIALS_H_
